services:
    symfony.application:
      class: Symfony\Component\Console\Application
      arguments:
        - 'dropcat'
        - '1.0.0-beta1'
    symfony.console_output:
      class: Symfony\Component\Console\Output\ConsoleOutput

    dropcat.configuration:
      class: Dropcat\Services\Configuration
      factory: ['Dropcat\Services\DropcatConfigurationFactory', createConfigurationService]
    dropcat.command.tar:
        class: Dropcat\Command\TarCommand
        arguments: ['@DropcatContainer','@dropcat.configuration']
        lazy: true
        tags:
          - {name: console.command, command: tar}
    dropcat.command.backup:
      class: Dropcat\Command\BackupCommand
      arguments: ['@DropcatContainer','@dropcat.configuration']
      lazy: true
      tags:
        - {name: console.command, command: backup}
    dropcat.command.config-import:
      class: Dropcat\Command\ConfigImportCommand
      arguments: ['@DropcatContainer','@dropcat.configuration']
      lazy: true
      tags:
        - {name: console.command, command: config-import}
    dropcat.command.db-import:
      class: Dropcat\Command\DbImportCommand
      arguments: ['@DropcatContainer','@dropcat.configuration']
      lazy: true
      tags:
        - {name: console.command, command: db-import}
    dropcat.command.move:
      class: Dropcat\Command\MoveCommand
      arguments: ['@DropcatContainer','@dropcat.configuration']
      lazy: true
      tags:
        - {name: console.command, command: move}
    dropcat.command.symlink:
      class: Dropcat\Command\SymlinkCommand
      arguments: ['@DropcatContainer','@dropcat.configuration']
      lazy: true
      tags:
        - {name: console.command, command: symlink}
    dropcat.command.upload:
      class: Dropcat\Command\UploadCommand
      arguments: ['@DropcatContainer','@dropcat.configuration']
      lazy: true
      tags:
        - {name: console.command, command: upload}
    dropcat.command.prepare:
      class: Dropcat\Command\PrepareCommand
      arguments: ['@DropcatContainer','@dropcat.configuration']
      lazy: true
      tags:
        - {name: console.command, command: prepare}
    dropcat.command.self-update:
      class: Dropcat\Command\SelfUpdaterCommand
      arguments: ['@DropcatContainer','@dropcat.configuration']
      lazy: true
      tags:
        - {name: console.command, command: self-update}
    dropcat.command.self-rollback:
      class: Dropcat\Command\SelfRollbackCommand
      arguments: ['@DropcatContainer','@dropcat.configuration']
      lazy: true
      tags:
        - {name: console.command, command: self-rollback}
    dropcat.command.init:
      class: Dropcat\Command\InitCommand
      arguments: ['@DropcatContainer','@dropcat.configuration']
      lazy: true
      tags:
        - {name: console.command, command: init}
    dropcat.command.init-wp:
      class: Dropcat\Command\InitWPCommand
      arguments: ['@DropcatContainer','@dropcat.configuration']
      lazy: true
      tags:
        - {name: console.command, command: init:wp}
    dropcat.command.about:
      class: Dropcat\Command\AboutCommand
      arguments: ['@DropcatContainer','@dropcat.configuration']
      lazy: true
      tags:
        - {name: console.command, command: about}
    dropcat.command.site-install:
      class: Dropcat\Command\SiteInstallCommand
      arguments: ['@DropcatContainer','@dropcat.configuration']
      lazy: true
      tags:
        - {name: console.command, command: site-install}
    dropcat.command.reset-login:
      class: Dropcat\Command\ResetLoginCommand
      arguments: ['@DropcatContainer','@dropcat.configuration']
      lazy: true
      tags:
        - {name: console.command}
    dropcat.command.jenkins-build:
      class: Dropcat\Command\JenkinsBuildCommand
      arguments: ['@DropcatContainer','@dropcat.configuration']
      lazy: true
      tags:
        - {name: console.command, command: jenkins-build}
    dropcat.command.entity-update:
      class: Dropcat\Command\EntityUpdateCommand
      arguments: ['@DropcatContainer','@dropcat.configuration']
      lazy: true
      tags:
        - {name: console.command, command: entity-update}
    dropcat.command.cache-recreate:
      class: Dropcat\Command\CacheRecreateCommand
      arguments: ['@DropcatContainer','@dropcat.configuration']
      lazy: true
      tags:
        - {name: console.command, command: cache-recreate}
    dropcat.command.cache-clear:
      class: Dropcat\Command\CacheClearCommand
      arguments: ['@DropcatContainer','@dropcat.configuration']
      lazy: true
      tags:
        - {name: console.command, command: cache-clear}
    dropcat.command.check-connection:
      class: Dropcat\Command\CheckConnectionCommand
      arguments: ['@DropcatContainer','@dropcat.configuration']
      lazy: true
      tags:
        - {name: console.command, command: check-connection}
    dropcat.command.create-drush-alias:
      class: Dropcat\Command\CreateDrushAliasCommand
      arguments: ['@DropcatContainer','@dropcat.configuration']
      lazy: true
      tags:
        - {name: console.command, command: create-drush-alias}
    dropcat.command.get:db-backup:
      class: Dropcat\Command\GetDatabaseBackupCommand
      arguments: ['@DropcatContainer','@dropcat.configuration']
      lazy: true
      tags:
        - {name: console.command}
    dropcat.command.node:npm-install:
      class: Dropcat\Command\RunNpmInstallCommand
      arguments: ['@DropcatContainer','@dropcat.configuration']
      lazy: true
      tags:
        - {name: console.command}
    dropcat.command.node:gulp:
      class: Dropcat\Command\RunGulpCommand
      arguments: ['@DropcatContainer','@dropcat.configuration']
      tags:
        - {name: console.command}
    dropcat.command.rsync:to:
      class: Dropcat\Command\RsyncToCommand
      arguments: ['@DropcatContainer','@dropcat.configuration']
      lazy: true
      tags:
        - {name: console.command}
    dropcat.command.rsync:from:
      class: Dropcat\Command\RsyncFromCommand
      arguments: ['@DropcatContainer','@dropcat.configuration']
      lazy: true
      tags:
        - {name: console.command}
    dropcat.command.run-remote:
      class: Dropcat\Command\RunRemoteCommand
      arguments: ['@DropcatContainer','@dropcat.configuration']
      lazy: true
      tags:
        - {name: console.command}
    dropcat.command.vhost:create:
      class: Dropcat\Command\VhostCreateCommand
      arguments: ['@DropcatContainer','@dropcat.configuration']
      lazy: true
      tags:
        - {name: console.command}
    dropcat.command.vhost:delete:
      class: Dropcat\Command\VhostDeleteCommand
      arguments: ['@DropcatContainer','@dropcat.configuration']
      lazy: true
      tags:
        - {name: console.command}
    dropcat.command.varnish-purge:
      class: Dropcat\Command\VarnishPurgeCommand
      arguments: ['@DropcatContainer','@dropcat.configuration']
      lazy: true
      tags:
        - {name: console.command}
    dropcat.command.tracker:
      class: Dropcat\Command\TrackerCommand
      arguments: ['@DropcatContainer','@dropcat.configuration']
      lazy: true
      tags:
        - {name: console.command}
    dropcat.command.rollback:
      class: Dropcat\Command\RollbackCommand
      arguments: ['@DropcatContainer','@dropcat.configuration']
      lazy: true
      tags:
        - {name: console.command}
    dropcat.command.multi:move:
      class: Dropcat\Command\MultiMoveCommand
      arguments: ['@DropcatContainer','@dropcat.configuration']
      lazy: true
      tags:
        - {name: console.command}

    dropcat.command.update:
      class: Dropcat\Command\UpdateCommand
      arguments: ['@DropcatContainer','@dropcat.configuration']
      lazy: true
      tags:
        - {name: console.command}
    dropcat.command.node:yarn-install:
      class: Dropcat\Command\RunYarnInstallCommand
      arguments: ['@DropcatContainer','@dropcat.configuration']
      lazy: true
      tags:
        - {name: console.command}
    dropcat.command.generate:drush-alias:
      class: Dropcat\Command\GenerateDrushAliasCommand
      arguments: ['@DropcatContainer','@dropcat.configuration']
      lazy: true
      tags:
        - {name: console.command}
    dropcat.command.init:drupal:
      class: Dropcat\Command\InitDrupalCommand
      arguments: ['@DropcatContainer','@dropcat.configuration']
      lazy: true
      tags:
        - {name: console.command}
    dropcat.command.init:wp:
      class: Dropcat\Command\InitWordpressCommand
      arguments: ['@DropcatContainer','@dropcat.configuration']
      lazy: true
      tags:
        - {name: console.command}
    dropcat.command.debug:check-connection:
      class: Dropcat\Command\DebugCheckConnectionCommand
      arguments: ['@DropcatContainer','@dropcat.configuration']
      lazy: true
      tags:
        - {name: console.command}
    dropcat.command.generate:config:
      class: Dropcat\Command\GenerateConfigCommand
      arguments: ['@DropcatContainer','@dropcat.configuration']
      lazy: true
      tags:
        - {name: console.command}
    dropcat.command.multi:list:
      class: Dropcat\Command\MultiListCommand
      arguments: ['@DropcatContainer','@dropcat.configuration']
      lazy: true
      tags:
            - {name: console.command}

    dropcat.command.scan:mixed-content:
      class: Dropcat\Command\MixedContentCommand
      arguments: ['@DropcatContainer','@dropcat.configuration']
      lazy: true
      tags:
            - {name: console.command, command: scan:mixed-content}
